const MYSTICS_METADATA = {
  "mystics": [
    {
      "id": 17,
      "name": "Holy Prayer",
      "subtype": 2,
      "subtype_name": "The High Priestess",
      "mc": 2,
      "pasted": "nonP",
      "interfere": true,
      "turns": 0,
      "rarity": "Common",
      "img": "OGcarddbmystic/card_17.jpg",
      "ability_text": ["เลือก 1 อย่าง", "★ รักษา Curse ทุกชนิดให้กับ Seal 1 ใบ", "★ ทำลาย Mystic Card ชนิด [PS] 1 ใบในสนาม"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    },
    {
      "id": 18,
      "name": "Galahad",
      "subtype": 7,
      "subtype_name": "The Chariot",
      "mc": 2,
      "pasted": "PS",
      "interfere": false,
      "turns": 999,
      "rarity": "Common",
      "img": "OGcarddbmystic/card_18.jpg",
      "ability_text": ["เลือก 1 อย่าง", "★ ถ้า Seal ที่ Galahad ติดคือ [Knight] → At +2", "★ ถ้า Seal ที่ Galahad ติดคือ [Wind] → At +2 Sp +1"],
      "exception_lv": 3,
      "exception_tribes": ["Machine"],
      "exception_els": []
    },
    {
      "id": 19,
      "name": "Crescent",
      "subtype": 18,
      "subtype_name": "The Moon",
      "mc": 2,
      "pasted": "PS",
      "interfere": false,
      "turns": 999,
      "rarity": "Common",
      "img": "OGcarddbmystic/card_19.jpg",
      "ability_text": ["เลือก 1 อย่าง", "★ ถ้า Seal ที่ Crescent ติดคือ [Dark] → At +2", "★ ถ้า Seal ที่ Crescent ติดคือ [Water] → At +1, Ma -1"],
      "exception_lv": 3,
      "exception_tribes": ["Machine"],
      "exception_els": []
    },
    {
      "id": 21,
      "name": "Holy Sun",
      "subtype": 19,
      "subtype_name": "The Sun",
      "mc": 2,
      "pasted": "PS",
      "interfere": false,
      "turns": 999,
      "rarity": "Common",
      "img": "OGcarddbmystic/card_21.jpg",
      "ability_text": ["เลือก 1 อย่าง", "★ ถ้า Seal ที่ Holy Sun ติดคือ [Light] → At +2", "★ ถ้า Seal ที่ Holy Sun ติดคือ [Fire] → At +2", "★ ถ้า Seal ที่ Holy Sun ติดคือ [Divine] → At +2"],
      "exception_lv": 3,
      "exception_tribes": ["Machine"],
      "exception_els": []
    },
    {
      "id": 24,
      "name": "Werrian Wesley",
      "subtype": 1,
      "subtype_name": "The Magician",
      "mc": 2,
      "pasted": "PS",
      "interfere": false,
      "turns": 999,
      "rarity": "Common",
      "img": "OGcarddbmystic/card_24.jpg",
      "ability_text": ["เลือก 1 อย่าง", "★ ถ้า Seal ที่ Werrian Wesley ติดคือ [Mage] → At +2", "★ ถ้า Seal ที่ Werrian Wesley ติดคือ [Earth] → At +2 Df +1"],
      "exception_lv": 3,
      "exception_tribes": ["Machine"],
      "exception_els": []
    },
    {
      "id": 25,
      "name": "Beauty & the Beast",
      "subtype": 8,
      "subtype_name": "Strength",
      "mc": 2,
      "pasted": "PS",
      "interfere": false,
      "turns": 999,
      "rarity": "Common",
      "img": "OGcarddbmystic/card_25.jpg",
      "ability_text": ["เลือก 1 อย่าง", "★ ถ้า Seal ที่ติดคือ [Monster] → At +2", "★ ถ้า Seal ที่ติดคือ [Beast] → At +2", "★ ถ้า Seal ที่ติดคือ [Dragon] → At +1"],
      "exception_lv": 3,
      "exception_tribes": ["Machine"],
      "exception_els": []
    },
    {
      "id": 26,
      "name": "Inquisition",
      "subtype": 5,
      "subtype_name": "The Hierophant",
      "mc": 2,
      "pasted": "nonP",
      "interfere": true,
      "turns": 0,
      "rarity": "Common",
      "img": "OGcarddbmystic/card_26.jpg",
      "ability_text": ["ทำลาย Mystic Card ใบอื่น 1 ใบในสนาม"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    },
    {
      "id": 27,
      "name": "Lighthouse",
      "subtype": 16,
      "subtype_name": "The Tower",
      "mc": 1,
      "pasted": "nonP",
      "interfere": true,
      "turns": 0,
      "rarity": "Common",
      "img": "OGcarddbmystic/card_27.jpg",
      "ability_text": ["เลือก 1 อย่าง", "★ ดูการ์ดทุกใบในมือฝ่ายตรงข้าม", "★ ดูการ์ดใบบนสุด 1 ใบของกองการ์ดเราทุกกอง"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    },
    {
      "id": 29,
      "name": "Release from Hell",
      "subtype": 15,
      "subtype_name": "The Devil",
      "mc": 2,
      "pasted": "PS",
      "interfere": false,
      "turns": 999,
      "rarity": "Common",
      "img": "OGcarddbmystic/card_29.jpg",
      "ability_text": ["ถ้า Seal ที่ Release from Hell ติดคือ [Evil] → At +2 Df +1 Sp +1"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    },
    {
      "id": 30,
      "name": "Houdini",
      "subtype": 12,
      "subtype_name": "The Hanged Man",
      "mc": 2,
      "pasted": "PS",
      "interfere": true,
      "turns": 1,
      "rarity": "Common",
      "img": "OGcarddbmystic/card_30.jpg",
      "ability_text": ["Seal ที่ Houdini ติด ติด Stone Curse"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    },
    {
      "id": 31,
      "name": "Yang",
      "subtype": 11,
      "subtype_name": "Justice",
      "mc": 2,
      "pasted": "PS",
      "interfere": true,
      "turns": 1,
      "rarity": "Common",
      "img": "OGcarddbmystic/card_31.jpg",
      "ability_text": ["Seal ที่ Yang ติด -Df ตาม Lv ของ Seal ใบนั้น"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    },
    {
      "id": 32,
      "name": "Yin",
      "subtype": 11,
      "subtype_name": "Justice",
      "mc": 2,
      "pasted": "PS",
      "interfere": true,
      "turns": 1,
      "rarity": "Common",
      "img": "OGcarddbmystic/card_32.jpg",
      "ability_text": ["Seal ที่ Yin ติด -At ตาม Lv ของ Seal ใบนั้น"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    },
    {
      "id": 33,
      "name": "Magical World",
      "subtype": 21,
      "subtype_name": "The World",
      "mc": 2,
      "pasted": "PS",
      "interfere": false,
      "turns": 999,
      "rarity": "Uncommon",
      "img": "OGcarddbmystic/card_33.jpg",
      "ability_text": ["เลือกธาตุ 1 ธาตุ จากนั้น Seal ที่ Magical World ติดนับว่ารวมร่างกับธาตุที่เลือก (ถ้าธาตุที่เลือกไม่ตรงตามเงื่อนไขการรวมร่าง ทำลาย Magical World)"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    },
    {
      "id": 34,
      "name": "Cunning Clown",
      "subtype": 0,
      "subtype_name": "The Fool",
      "mc": 2,
      "pasted": "PA",
      "interfere": false,
      "turns": 0,
      "rarity": "Uncommon",
      "img": "OGcarddbmystic/card_34.jpg",
      "ability_text": ["ผู้เล่นฝ่ายตรงข้ามสลับ Seal ทุกใบ (ไม่ใช่ [Machine]) ระหว่าง At Line และ Df Line"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    },
    {
      "id": 35,
      "name": "Nebuchadnezzar",
      "subtype": 4,
      "subtype_name": "The Emperor",
      "mc": 3,
      "pasted": "PA",
      "interfere": false,
      "turns": 999,
      "rarity": "Uncommon",
      "img": "OGcarddbmystic/card_35.jpg",
      "ability_text": ["เราจำนวนการ์ดในมือสูงสุด +1"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    },
    {
      "id": 36,
      "name": "Silent Prohibitor",
      "subtype": 9,
      "subtype_name": "The Hermit",
      "mc": 2,
      "pasted": "PS",
      "interfere": false,
      "turns": 1,
      "rarity": "Uncommon",
      "img": "OGcarddbmystic/card_36.jpg",
      "ability_text": ["Seal ที่ Silent Prohibitor ติด ป้องกัน Mystic Card, Skill, การโจมตี และการถูกทำลายจากการสวนกลับ"],
      "exception_lv": null,
      "exception_tribes": ["Evil"],
      "exception_els": ["darkness"]
    },
    {
      "id": 37,
      "name": "Thunder Bolt",
      "subtype": 16,
      "subtype_name": "The Tower",
      "mc": 3,
      "pasted": "PS",
      "interfere": true,
      "turns": 0,
      "rarity": "Uncommon",
      "img": "OGcarddbmystic/card_37.jpg",
      "ability_text": ["Seal ที่ Thunder Bolt ติด แยกการรวมร่าง"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    },
    {
      "id": 38,
      "name": "Whirl to Win",
      "subtype": 10,
      "subtype_name": "Wheel of Fortune",
      "mc": 3,
      "pasted": "PS",
      "interfere": true,
      "turns": 1,
      "rarity": "Uncommon",
      "img": "OGcarddbmystic/card_38.jpg",
      "ability_text": ["Seal ที่ Whirl to Win ติด สลับ At กับ Df"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    },
    {
      "id": 39,
      "name": "Chaotic World",
      "subtype": 21,
      "subtype_name": "The World",
      "mc": 2,
      "pasted": "PS",
      "interfere": true,
      "turns": 999,
      "rarity": "Uncommon",
      "img": "OGcarddbmystic/card_39.jpg",
      "ability_text": ["เลือกธาตุ 1 ธาตุ จากนั้น Seal ที่ Chaotic World ติดเปลี่ยนเป็นธาตุที่เลือก"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": ["divine"]
    },
    {
      "id": 40,
      "name": "Benediction",
      "subtype": 20,
      "subtype_name": "Judgement",
      "mc": 3,
      "pasted": "nonP",
      "interfere": false,
      "turns": 0,
      "rarity": "Uncommon",
      "img": "OGcarddbmystic/card_40.jpg",
      "ability_text": ["นำ Seal 1 ใบใน Shrine เราขึ้นมือ"],
      "exception_lv": null,
      "exception_tribes": ["Evil", "Machine"],
      "exception_els": []
    },
    {
      "id": 61,
      "name": "Seven Silver",
      "subtype": 17,
      "subtype_name": "The Star",
      "mc": 3,
      "pasted": "PS",
      "interfere": false,
      "turns": 1,
      "rarity": "Uncommon",
      "img": "OGcarddbmystic/card_61.jpg",
      "ability_text": ["Seal ที่ Seven Silver ติดสามารถใช้ท่าโจมตีได้ 2 ครั้ง โดยจ่าย Mp ค่าโจมตีเพียงครั้งเดียว"],
      "exception_lv": 4,
      "exception_tribes": ["Machine"],
      "exception_els": []
    },
    {
      "id": 66,
      "name": "Sacrifice",
      "subtype": 13,
      "subtype_name": "Death",
      "mc": 5,
      "pasted": "nonP",
      "interfere": false,
      "turns": 0,
      "rarity": "Rare",
      "img": "OGcarddbmystic/card_66.jpg",
      "ability_text": ["ทำลาย Seal 1 ใบในสนาม และทิ้ง Seal 2 ใบจากมือเรา"],
      "exception_lv": null,
      "exception_tribes": ["Machine"],
      "exception_els": []
    },
    {
      "id": 68,
      "name": "Will of True Mind",
      "subtype": 14,
      "subtype_name": "Temperance",
      "mc": 2,
      "pasted": "PS",
      "interfere": false,
      "turns": 0,
      "rarity": "Rare",
      "img": "OGcarddbmystic/card_68.jpg",
      "ability_text": ["Seal ที่ Will of True Mind ติดสามารถใช้ท่าโจมตีหรือ Skill ได้โดยไม่ต้องตรงตามเงื่อนไขการรวมร่าง 1 ครั้งใน Subturn นี้"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    },
    {
      "id": 69,
      "name": "Cupid and Psyche",
      "subtype": 6,
      "subtype_name": "The Lovers",
      "mc": 4,
      "pasted": "PS",
      "interfere": false,
      "turns": 999,
      "rarity": "Rare",
      "img": "OGcarddbmystic/card_69.jpg",
      "ability_text": ["Seal ที่ Cupid and Psyche ติด ติด Charm Curse"],
      "exception_lv": 3,
      "exception_tribes": ["Machine"],
      "exception_els": ["light"]
    },
    {
      "id": 70,
      "name": "Marie Antoinette",
      "subtype": 3,
      "subtype_name": "The Empress",
      "mc": 3,
      "pasted": "PA",
      "interfere": false,
      "turns": 999,
      "rarity": "Rare",
      "img": "OGcarddbmystic/card_70.jpg",
      "ability_text": ["เรา Mp สูงสุด +1 และ การ์ดในมือสูงสุด -1"],
      "exception_lv": null,
      "exception_tribes": [],
      "exception_els": []
    }
  ]
}

;